/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoVideoIdIndexRouteImport } from './routes/video/$videoId.index'
import { Route as VideoVideoIdEditRouteImport } from './routes/video/$videoId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdIndexRoute = VideoVideoIdIndexRouteImport.update({
  id: '/video/$videoId/',
  path: '/video/$videoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVideoIdEditRoute = VideoVideoIdEditRouteImport.update({
  id: '/video/$videoId_/edit',
  path: '/video/$videoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video/$videoId/edit': typeof VideoVideoIdEditRoute
  '/video/$videoId': typeof VideoVideoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video/$videoId/edit': typeof VideoVideoIdEditRoute
  '/video/$videoId': typeof VideoVideoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video/$videoId_/edit': typeof VideoVideoIdEditRoute
  '/video/$videoId/': typeof VideoVideoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video/$videoId/edit' | '/video/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video/$videoId/edit' | '/video/$videoId'
  id: '__root__' | '/' | '/video/$videoId_/edit' | '/video/$videoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoVideoIdEditRoute: typeof VideoVideoIdEditRoute
  VideoVideoIdIndexRoute: typeof VideoVideoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId/': {
      id: '/video/$videoId/'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$videoId_/edit': {
      id: '/video/$videoId_/edit'
      path: '/video/$videoId/edit'
      fullPath: '/video/$videoId/edit'
      preLoaderRoute: typeof VideoVideoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoVideoIdEditRoute: VideoVideoIdEditRoute,
  VideoVideoIdIndexRoute: VideoVideoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
